#ifndef ENUMS_H
#define ENUMS_H

enum Interval : int {
    UNISON= 0,
    MINOR_SECOND,
    MAJOR_SECOND,
    MINOR_THIRD,
    MAJOR_THIRD,
    PERFECT_FOURTH,
    DIMINISHED_FIFTH,
    PERFECT_FIFTH,
    MINOR_SIXTH,
    MAJOR_SIXTH,
    MINOR_SEVENTH,
    MAJOR_SEVENTH,
    OCTAVE,
    NONE = 99,
};

#endif
